name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request] - <title>"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
    validations:
      required: true