name: Deploy Document

on:
  push:
    branches: [master]
    paths:
      - 'document/**'
  pull_request:
    branches: [master]
    paths:
      - 'document/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: cd document && bun install
      - name: Build with VitePress
        run: cd document && bun run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./document/.vitepress/dist